

package database;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Paths;

public class TXTExport {
	
	public void export(String path) throws IOException {
		
		PrintWriter writer = new PrintWriter(path + ".txt");
		
		File file = new File("C:\\AnimeWatchList\\Database");
		File[] listOfFilesGesehen = file.listFiles();
		int animecount = file.list().length;
		
		writer.println("_________________________________________________________________"); 
		writer.println("|                                                               |"); 
		writer.println("|                          Gesehen                              |"); 
		writer.println("|_______________________________________________________________|");
		
		int gesehen = 0;
		int nichtgesehen = 0;
		
		for(int i = 1; i < animecount; i++) {
			String filename = listOfFilesGesehen[i].getName() + "";	
			filename = filename.substring(0, filename.lastIndexOf("."));

			if(Files.readAllLines(Paths.get("C:\\AnimeWatchList\\Database\\" + filename + ".anime")).get(3).equals("true")) {
				int strlength = filename.length();
				int length = 58;
				int calclength = length - strlength;
				 
				gesehen++;
					
				writer.print("|" + gesehen);
					
				if(!(gesehen >= 10)) {
					writer.print(" ");
				}
				writer.print("| " + filename);
				
				for(int i1 = 0; i1 <= calclength; i1++) {
					writer.print(" "); 
				}
				writer.print("|");
				writer.println("");
			} 
		}

		writer.println("|__|____________________________________________________________|"); 
		writer.println("|                                                               |"); 
		writer.println("|                         nicht Gesehen                         |");
		writer.println("|_______________________________________________________________|");
		
		for(int i = 1; i < animecount; i++) {
			String filename = listOfFilesGesehen[i].getName() + "";	
			filename = filename.substring(0, filename.lastIndexOf("."));
	
			if(Files.readAllLines(Paths.get("C:\\AnimeWatchList\\Database\\" + filename + ".anime")).get(3).equals("false")) {
				int strlength = filename.length();
				int length = 58;
				int calclength = length - strlength;
			 
				nichtgesehen++;
				
				writer.print("|" + nichtgesehen);
				
				if(!(nichtgesehen >= 10)) {
					writer.print(" ");
				}
				writer.print("| " + filename);
				
				for(int i1 = 0; i1 <= calclength; i1++) {
					writer.print(" "); 
				}
				writer.print("|");
				writer.println("");
			}	
		}
		
		writer.println("|*_|____________________________________________________________|"); 
		
			
	writer.println("generated a List of " + (gesehen + nichtgesehen) + " Animes.");
	
	for(int i = 0; i <= 5; i++) {
		writer.println(" ");
	}
	
		writer.print("\nGenerated by the Anime Watch list by potzplitz");
		writer.close();	
	}

}